apiVersion: v1
kind: Service
metadata:
  name: ewrgfdr4
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ewrgfdr4"
    port: 8080
  selector:
    app: ewrgfdr4
